env=dev,
onboarding_project_Name='MFTPatterns/project-onboard-file-transfer_dev'
Job_name='trailVersion'
intDetails='""'
Remarks='trailVersion'
domain='DEV'
project_Name='/MFTPatterns/project-sftp-inbound-sftp-ftransfer_qa'