env=qa,
onboarding_project_Name='MFTPatterns/project-onboard-file-transfer_qa'
Job_name='M.Tech_Final_Year_Project'
intDetails='""'
Remarks='M.Tech_Final_Year_Project'
domain='QA'
project_Name='/MFTPatterns/project-sftp-outbound-sftp-ftransfer_qa'