env=qa,
onboarding_project_Name='MFTPatterns/project-onboard-file-transfer_qa'
Job_name='APIM-LOGICAPP'
intDetails='"{\"flowDirection\":\"string\",\"internalerrorEmailNotification\":\"string\",\"projectName\":\"string\",\"workSpacePath\":\"string\",\"fileTransfer\":\"string\",\"sourceDetails\":{\"host\":\"string\",\"sshKeyRequired\":\"string\",\"ssh\":{\"keyVault\":\"string\",\"keyName\":\"string\",\"keyPassword\":\"string\",\"rsaKeySignatureAlgorithm\":\"string\"},\"pgp\":{\"keyName\":\"string\"}},\"targetDetails\":{\"host\":\"string\",\"deleteRequired\":\"string\",\"ssh\":{\"keyVault\":{},\"rsaKeySignatureAlgorithm\":\"string\"},\"pgp\":{\"keyName\":\"string\"}}}"'
Remarks='APIM-LOGICAPP'
domain='QA'
project_Name='/MFTPatterns/project-sftp-inbound-sftp-ftransfer_qa'