env=qa,
onboarding_project_Name='MFTPatterns/project-onboard-file-transfer_qa'
Job_name='trailversion'
intDetails='""'
Remarks='trailversion'
domain='QA'
project_Name='/MFTPATTERN/project-sftp-inbound-sftp-ftransfer_qa'