env=PreProduction,
onboarding_project_Name='MFTPatterns/project-onboard-file-transfer_preprod'
Job_name='dert-oers'
intDetails='""'
Remarks='dert-oers'
domain='PreProduction'
project_Name='/MFTPatterns/project-sftp-inbound-sftp-ftransfer_preprod'